"""
Step 2: Extract structured methodology information from a Docling Markdown paper.

Input:
    Path to a Markdown file generated by Docling (e.g. outputs/MAINPAPER.md)
    or raw markdown text string.

Output:
    A fixed dictionary containing the methodology information we want
    for every paper.

Pipeline:
    Markdown (from Docling)
      ↓
    Section-wise splitting
      ↓
    Gemini extraction for each section
      ↓
    Merge into one dictionary
      ↓
    Save structured JSON to outputs/
"""

import os
import sys
import glob
import json
import time
from dotenv import load_dotenv, find_dotenv
from google import genai
from google.genai import types
from pydantic import BaseModel, Field

load_dotenv(find_dotenv())
load_dotenv(".env")
load_dotenv("../.env")

MODEL = os.getenv("GEMINI_MODEL", "gemini-3.6-flash")

class ExtractionResult(BaseModel):
    task_type: str = Field(default="not reported")
    dataset: str = Field(default="not reported")
    data_split: str = Field(default="not reported")
    preprocessing: str = Field(default="not reported")
    method: str = Field(default="not reported")
    baselines: str = Field(default="not reported")
    metrics: str = Field(default="not reported")
    results: str = Field(default="not reported")
    main_claims: str = Field(default="not reported")
    limitations: str = Field(default="not reported")

def get_gemini_client():
    api_key = os.getenv("GEMINI_API_KEY") or os.getenv("GOOGLE_API_KEY")
    if not api_key:
        raise ValueError("Gemini API key not found.")
    return genai.Client(api_key=api_key)

def extract_paper_context(paper_markdown: str, client=None):
    """
    Single-call extraction for free-tier safety.
    We keep the prompt compact and trim the paper so we don't hit quota.
    """
    if client is None:
        client = get_gemini_client()

    # Keep a conservative size to avoid token overuse on free plan
    max_chars = 15000
    compact_markdown = paper_markdown[:max_chars]

    prompt = f"""
You are extracting methodology information from an ML research paper.

Use only information explicitly stated in the paper.
If a field is not mentioned, return "not reported".

Return valid JSON matching this schema:
{json.dumps(ExtractionResult.model_json_schema(), indent=2)}

PAPER TEXT:
{compact_markdown}
"""

    try:
        response = client.models.generate_content(
            model=MODEL,
            contents=prompt,
            config=types.GenerateContentConfig(
                temperature=0,
                response_mime_type="application/json",
                response_schema=ExtractionResult,
            ),
        )

        if getattr(response, "parsed", None) is not None:
            if isinstance(response.parsed, BaseModel):
                return response.parsed.model_dump()
            return response.parsed

        if getattr(response, "text", None):
            return json.loads(response.text)

        raise RuntimeError("Gemini returned no parsed output.")

    except Exception as e:
        err = str(e).lower()
        if "429" in err or "resource_exhausted" in err or "rate limit" in err:
            raise RuntimeError(
                "Gemini rate limit hit during extraction. "
                "Your free-tier quota is exhausted. "
                "Reduce request count or use a paid quota."
            ) from e
        raise

# ============================================================
# CLI entry point
# ============================================================

if __name__ == "__main__":
    md_path = None

    if len(sys.argv) > 1:
        md_path = sys.argv[1]
    else:
        available_mds = glob.glob("outputs/*.md") + glob.glob("backend/outputs/*.md")
        if available_mds:
            md_path = max(available_mds, key=os.path.getmtime)
            print(f"No markdown file specified. Using latest found: {md_path}")
        else:
            print("Usage: python extract.py <path_to_markdown_file>")
            sys.exit(1)

    if not os.path.exists(md_path):
        print(f"Error: File '{md_path}' does not exist.")
        sys.exit(1)

    print(f"\nReading Markdown from: {md_path}")
    with open(md_path, "r", encoding="utf-8") as f:
        markdown = f.read()

    try:
        context = extract_paper_context(markdown)
    except Exception as err:
        print(f"\n[Extraction Error]: {err}")
        sys.exit(1)

    base_name = os.path.splitext(os.path.basename(md_path))[0]
    out_dir = os.path.dirname(md_path) or "outputs"
    json_path = os.path.join(out_dir, f"{base_name}_extracted.json")

    with open(json_path, "w", encoding="utf-8") as out_f:
        json.dump(context, out_f, indent=2, ensure_ascii=False)

    print(f"\nSuccessfully saved structured extraction to: {json_path}")
    print(json.dumps(context, indent=2, ensure_ascii=False))
