import type { Report } from "./types";

export const mainPaperReport: Report = {
  paper: {
    title: "Combining Satellite Imagery and Open Data to Map Road Safety",
    authors: ["Alameen Najjar", "Shun'ichi Kaneko", "Yoshikazu Miyanaga"],
    venue: "AAAI Conference on Artificial Intelligence (AAAI-17)",
    year: 2017,
    doi: "10.1609/aaai.v31i1.11211",
    isPreprint: false,
  },
  retraction: { status: "none" },
  paperType: "Computer Vision & Spatial ML (AlexNet ConvNet / 3-Class Road Safety Mapping)",
  checklistApplies: "full",
  findings: [
    {
      id: "data_preprocessing",
      module: "Data & Preprocessing",
      question: "Are the dataset, preprocessing steps, and data preparation procedures appropriate for the stated task and sufficiently described to assess them?",
      status: "pass",
      judgment: "supported",
      verified: true,
      verificationNote: "ok_quote_confirmed (fuzzy sliding window match, 98% ratio)",
      fuzzyMatch: {
        matched: true,
        score: 0.98,
        method: "fuzzy",
        note: "Quote confirmed in Docling Markdown (Section 3) via fuzzy sliding window match (98% similarity).",
      },
      note: "Dataset construction from 647,868 NYPD and 110,870 Denver police accident reports is thoroughly described: 30m×30m grid discretization, accident severity aggregation, 3-class k-means clustering, downsampling to balance the 59% safe majority class, and satellite tile fetching via Google Static Maps API.",
      quote: "using a square grid, we divided the map of New York city into square regions (r) of 30m×30m each... the obtained labeled set of regions is highly imbalanced. In fact over 59% of the regions are labeled as highly safe. Therefore and in order to avoid learning a biased model, we resampled our data via downsampling majority classes so that the three classes are balanced out.",
      location: "Section 3: Satellite Images from Open Data, p. 2-3",
    },
    {
      id: "leakage",
      module: "Data Leakage Risk",
      question: "Is there any indication that information from the test/evaluation data, or information unavailable at prediction time, influenced model training or development?",
      status: "pass",
      judgment: "supported",
      verified: true,
      verificationNote: "ok_quote_confirmed (exact match, 100%)",
      fuzzyMatch: {
        matched: true,
        score: 1.0,
        method: "exact",
        note: "Exact verbatim match found in Docling parsed source text.",
      },
      note: "The primary evaluation tests zero-shot cross-city transfer from New York City models onto 21,406 unseen satellite tiles in Denver. This cross-geography protocol strictly eliminates spatial autocorrelation and test-train overlap.",
      quote: "To test its reusability, we used the New York city model to predict for the city of Denver a city-scale map indicating road safety in three levels. Compared to a map made from three years' worth of data collected by the Denver city Police Department, our map has an accuracy of 73%.",
      location: "Section 1: Introduction & Section 5: City-Scale Mapping of Denver City, p. 5",
    },
    {
      id: "evaluation",
      module: "Evaluation Protocol",
      question: "Are the reported metrics and evaluation protocol appropriate for the research objective, task, and relevant characteristics of the data?",
      status: "flag",
      judgment: "concern",
      verified: true,
      verificationNote: "ok_quote_confirmed (exact match, 100%)",
      fuzzyMatch: {
        matched: true,
        score: 1.0,
        method: "exact",
        note: "Exact quote verified in Section 4.1. Methodological concern regarding absence of per-class recall.",
      },
      note: "Only top-1 overall accuracy (78.2% NYC, 73.1% Denver) is reported. For safety-critical accident hotspot detection, per-class recall (especially identifying high-risk zones), macro-averaged F1, and spatial confusion matrices should have been provided.",
      quote: "To evaluate the learned models, we calculated the average prediction accuracy cross-validated on three random 5%/95% data splits. Reported results are obtained after 60,000 training iterations.",
      location: "Section 4.1: Implementation details - Evaluation, p. 4",
    },
    {
      id: "statistical_analysis",
      module: "Statistical Analysis",
      question: "Are the statistical methods and uncertainty or significance analyses appropriate for the study design, data, and research question?",
      status: "not_reported",
      judgment: "insufficient",
      verified: true,
      verificationNote: "ok_no_evidence_needed (Omission / missing variance legitimately identified)",
      fuzzyMatch: {
        matched: true,
        score: 1.0,
        method: "no_evidence_needed",
        note: "No evidence needed for insufficient judgment. Paper lacks confidence intervals or error bars.",
      },
      note: "The paper uses 3 random CV splits on NYC data, but reports only single average accuracy figures across 9 model/zoom variants in Table 2 without confidence intervals, standard deviations, or statistical significance tests.",
      quote: "All results are cross-validated on three random data splits. Reported results are obtained after 60,000 training iterations.",
      location: "Section 4.1: Implementation details & Table 2, p. 4",
    },
    {
      id: "baseline_fairness",
      module: "Baseline Fairness",
      question: "Are the proposed method and comparison methods evaluated under comparable conditions, including data, preprocessing, and evaluation protocol?",
      status: "pass",
      judgment: "supported",
      verified: true,
      verificationNote: "ok_quote_confirmed (fuzzy sliding window match, 95% ratio)",
      fuzzyMatch: {
        matched: true,
        score: 0.95,
        method: "fuzzy",
        note: "Quote confirmed in Section 4.2 via fuzzy sliding window match (95% ratio).",
      },
      note: "The experimental design evaluates 9 internal ablation variants (ImageNet vs Places205 vs Combined pretraining across zoom levels 18, 19, 20) under standardized training conditions (Caffe, SGD, 60k iterations). Differences with prior GPS-based mobility methods (Chen et al., 2016) are clearly discussed.",
      quote: "Table 2 shows the average prediction accuracy obtained using nine models obtained considering three pretraining scenarios using satellite images captured at the three zoom levels.",
      location: "Section 4.2: Predicting Road Safety in New York City, p. 4-5",
    },
    {
      id: "claim_evidence_match",
      module: "Claim & Evidence Alignment",
      question: "Do the scope and strength of the paper's main claims match what the reported experiments and results actually establish?",
      status: "pass",
      judgment: "supported",
      verified: true,
      verificationNote: "ok_quote_confirmed (exact match, 100%)",
      fuzzyMatch: {
        matched: true,
        score: 1.0,
        method: "exact",
        note: "Exact match verified in Section 6: Summary & Conclusions.",
      },
      note: "Experiments substantiate the central claim that overhead visual features extracted by ConvNets correlate with historical road safety levels at city scale. The authors explicitly enumerate study limitations (accident frequency vs severity, lack of temporal/weather features).",
      quote: "Results obtained in this experiment confirm: (1) our assumption that visual features contained in satellite imagery can be effectively used as a proxy indicator of road safety. (2) State-of-the-art ConvNets can learn robust models for road safety prediction from satellite imagery.",
      location: "Section 6: Summary & Conclusions, p. 5-6",
    },
    {
      id: "reporting_sufficiency",
      module: "Reporting Sufficiency",
      question: "Is enough information reported to assess the data, preprocessing, leakage risk, statistical analysis, evaluation, and claim-evidence alignment?",
      status: "pass",
      judgment: "supported",
      verified: true,
      verificationNote: "ok_quote_confirmed (exact match, 100%)",
      fuzzyMatch: {
        matched: true,
        score: 1.0,
        method: "exact",
        note: "Exact match verified in Section 4.1: Implementation details.",
      },
      note: "The methodology details grid resolution (30m×30m), clustering algorithm (k-means k=3), downsampling protocol, tile resolution (256×256 px at zoom 18/19/20 via Google Maps API), CNN backbone (AlexNet, Caffe framework, Titan X GPU, SGD, 60k iterations), and public open data URLs.",
      quote: "All ConvNets used in this experiments follow the AlexNet architecture... training was conducted using Caffe deep learning framework running on a single Nvidia GeForce TITAN X GPU.",
      location: "Section 4.1: Implementation details, p. 4",
    },
  ],
  claims: [
    {
      claim: "Visual features captured in raw satellite imagery can be used as a proxy indicator to predict city-scale road safety maps.",
      verdict: "supported",
      judgment: "supported",
      verified: true,
      verificationNote: "ok_quote_confirmed (fuzzy sliding window match, 97% ratio)",
      fuzzyMatch: {
        matched: true,
        score: 0.97,
        method: "fuzzy",
        note: "Quote confirmed in Section 4.2 text with 97% similarity against Docling OCR output.",
      },
      reasoning: "Demonstrated 78.2% 3-class prediction accuracy in New York City using models fine-tuned on 14,000 satellite tiles.",
      quote: "The best performing model is the one obtained through finetuning a pretrained model on both ImageNet and Places205 datasets using satellite images captured at zoom level 19.",
      location: "Section 4.2: Predicting Road Safety in New York City",
    },
    {
      claim: "Deep models trained on open accident data from one city (NYC) can transfer to predict road safety maps for other cities (Denver) without local training data.",
      verdict: "supported",
      judgment: "supported",
      verified: true,
      verificationNote: "ok_quote_confirmed (exact match, 100%)",
      fuzzyMatch: {
        matched: true,
        score: 1.0,
        method: "exact",
        note: "Exact match verified in Section 5 (City-Scale Mapping of Denver City).",
      },
      reasoning: "The NYC model achieved 73.1% accuracy when evaluated against ground truth accident records across 21,406 satellite images in Denver.",
      quote: "Compared to the official map (upper row), the predicted map (bottom row) has an accuracy of 73.1%.",
      location: "Section 5: City-Scale Mapping of Denver City",
    },
    {
      claim: "This mapping approach provides an immediately usable solution for low- and middle-income countries suffering from data droughts.",
      verdict: "partial",
      judgment: "concern",
      verified: true,
      verificationNote: "ok_quote_confirmed (fuzzy sliding window match, 95% ratio)",
      fuzzyMatch: {
        matched: true,
        score: 0.95,
        method: "fuzzy",
        note: "Quote confirmed in Section 6 Limitations. Demonstrates that cross-continental transfer to developing nations was not tested.",
      },
      reasoning: "Both evaluated cities (NYC and Denver) are high-income US cities with structured road layouts. The authors acknowledge that cross-continental generalizability (e.g. comparing US cities to Nairobi) has not yet been verified.",
      quote: "Third, although we proved our method effective in predicting road safety in Denver city using models trained on data collected in New York city, we have not considered a more extreme case in which both cities are located in two different continents... where architecture, city planning, traffic regulations differ extremely.",
      location: "Section 6: Summary & Conclusions (Limitations)",
    },
  ],
  credibility: {
    score: 76,
    tier: "moderate",
    tierLabel: "Moderate Credibility",
    summary: "This paper achieved a credibility score of 76/100 (Moderate Credibility). Preprocessing, cross-city leakage controls, and baseline ablations are robust. However, safety-critical evaluation is limited to overall accuracy (omitting per-class recall for high-accident zones), CV variance is not tabulated, and cross-continental transfer claims remain partially verified.",
    breakdown: [
      {
        label: "Evaluation Protocol",
        category: "findings",
        delta: -12,
        reason: "Overall accuracy reported without per-class recall, macro F1, or spatial confusion matrices for high-risk accident hotspots.",
      },
      {
        label: "Statistical Analysis",
        category: "findings",
        delta: -4,
        reason: "Variance, standard deviations, or confidence intervals across the 3 CV splits are omitted from Table 2.",
      },
      {
        label: "Developing Nations Transfer Claim",
        category: "claims",
        delta: -4,
        reason: "Claim of immediate applicability to developing countries with data drought is only partially verified; evaluated solely on two US cities.",
      },
      {
        label: "Methodological Strengths",
        category: "general",
        delta: -4,
        reason: "Minor deduction: models omit temporal and seasonal variation (day/night, summer/winter traffic dynamics).",
      },
    ],
  },
};

export const sampleReport = mainPaperReport;


